#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     joy1,           sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     motorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorC,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorD,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{
	servo[servo1] = 0;
	servo[servo2] = 50;
  return;
}

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  getJoystickSettings(joystick);
	  //Defines eff (speed multiplier)
	  /*int eff = 1;*/

	  //Stops left motor from breaching 100 or -100
	  if(abs(joystick.joy1_y1) <= 100){
	    motor[motorL] = joystick.joy1_y1 /* * eff */;
	  }

    //Stops right motor from breaching 100 or -100
		if(abs(joystick.joy1_y2) <= 100){
	    motor[motorR] = joystick.joy1_y2 /* * eff */;
	  }

	    //Adjusts eff
	  /*if(joy1Btn(6) && eff < 2){
	  	eff = eff + 0.2;
  	} else if(joy1Btn(5) && eff > 0){
  	  eff = eff - 0.2;
  	}*/

  	//Moves lift arm up and down w/ 2 speed options
  	//left == fast, right == slow
  	//Also can be controlled by joy1
  	if(joy2Btn(6)) {
  		motor[motorC] = 50;
  	} else if(joy2Btn(8)) {
  	  motor[motorC] = -50;
  	} else if(joy2Btn(5)){
  		motor[motorC] = 100;
  	} else if(joy2Btn(7)){
  		motor[motorC] = -100;
  	} else if(joy1Btn(6)){
  		motor[motorC] = 10;
  	} else if(joy1Btn(8)){
  		motor[motorC] = -10;
  	} else {
  		motor[motorC] = 0;
  	}

  	//Gyrator 2 directions 2 speeds

  	if(joy2Btn(1)){
  		motor[motorD] = 100;
  	} else if(joy2Btn(2)){
  	  motor[motorD] = -100;
  	} else if(joy2Btn(3)){
  		motor[motorD] = 5;
  	} else if(joy2Btn(4)){
  		motor[motorD] = -5;
  	} else {
  		motor[motorD] = 0;
  	}

  	if(joy2Btn(10) && joy1Btn(10))
  	{
  		servo[servo1] = 180;
  	} else if(joy2Btn(9)){
  		servo[servo1] = 0;
  	}

  }
}
