#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Flipper,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Tilter,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     FR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     Belt,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "sensors.h"

void initializeRobot()
{
	initInfrared();
  return;
}
void forward()
	{
		motor[FL] = 50;
		motor[FR] = -35;
		motor[BL] = 50;
		motor[BR] = -35;
	}

	void right2()
	{
		motor[FL] = 50;
		motor[FR] = 50;
		motor[BL] = -37;
		motor[BR] = -37;

	}

	void left()
	{
		motor[FL] = -60;
		motor[BL] = 60;
		motor[FR] = -60;
		motor[BR] = 60;
	}

	void back()
	{
	motor[FL] = -50;
		motor[FR] = 35;
		motor[BL] = -50;
		motor[BR] = 35;
	}

	void spinright()
	{
		motor[FL] = 60;
		motor[BL] = 60;
		motor[FR] = 60;
		motor[BR] = 60;
	}

	void feed()
	{
		motor[Belt] = -60;
	}

	void stopAll() {
		motor[FR] = motor[BR] = motor[BL] = motor[FL] = motor[Belt] = motor[Tilter] = 0;
	}

void waitForIR() {
	while(SensorValue[IR] < 600)
		wait1Msec(2);
	return;
}

task main()
{
  initializeRobot();

 // waitForStart();

  	motor[Tilter] = 80; // make robot upright
  	wait10Msec(75);
  	motor[Tilter] = 0;
  	right2();
  	wait10Msec(80);
  	stopAll();
  	wait10Msec(60);
  	updateInfrared();//IR 1
  	if (getInfraredZ3() > 100)
  	{motor[Flipper] = 50;
  		wait10Msec(75);
  		motor[Flipper] = 0;
  		forward();
  		wait10Msec(50);
  		stopAll();
  		motor[Flipper] = -100;
  		wait10Msec(20);
  		motor[Flipper] = 0;
  		feed();
  		wait10Msec(200);
  		stopAll();
  		back();
  		wait10Msec(30);
  		stopAll();
  		// left();//go to ramp 1
  		wait10Msec(60);
  		stopAll();
  	}
  	else
  	{	right2();
  	wait10Msec(75);
  	stopAll();
  	wait10Msec(60);
  	updateInfrared();//IR 2
  	if (getInfraredZ3() > 100)
  	{motor[Flipper] = 50;
  		wait10Msec(75);
  		motor[Flipper] = 0;
  		forward();
  		wait10Msec(50);
  		stopAll();
  		motor[Flipper] = -100;
  		wait10Msec(20);
  		motor[Flipper] = 0;
  		feed();
  		wait10Msec(200);
  		stopAll();
  		back();
  		wait10Msec(30);
  		stopAll();
  		// left();// go to ramp 2
  		wait10Msec(100);
  		stopAll();
  	}
		else
  	{	right2();
  	wait10Msec(60);
  	stopAll();
  	wait10Msec(80);
  	updateInfrared();//IR 3
  	if (getInfraredZ3() > 100)
  	{motor[Flipper] = 50;
  		wait10Msec(75);
  		motor[Flipper] = 0;
  		forward();
  		wait10Msec(50);
  		stopAll();
  		motor[Flipper] = -100;
  		wait10Msec(20);
  		motor[Flipper] = 0;
  		feed();
  		wait10Msec(200);
  		stopAll();
  		back();
  		wait10Msec(30);
  		stopAll();
  		// left();//go to ramp 3
  		wait10Msec(170);
  		stopAll();
  	}
  	else
  	{	right2();
  	wait10Msec(50);
  	stopAll(); // no IR just assumes that 4th basket is there
  	wait10Msec(60);
  	motor[Flipper] = 50;
  		wait10Msec(75);
  		motor[Flipper] = 0;
  		forward();
  		wait10Msec(80);
  		stopAll();
  		motor[Flipper] = -100;
  		wait10Msec(20);
  		motor[Flipper] = 0;
  		feed();
  		wait10Msec(200);
  		stopAll();
  		back();
  		wait10Msec(60);
  		stopAll();
  		// left();// go to ramp 4
  		wait10Msec(220);
  		stopAll();

}
}
}
//forward();
wait10Msec(130);
stopAll();
//right();
wait10Msec(150);
stopAll();
}
