#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Tilter,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lbelt,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     FR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     Rbelt,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{

  return;
}
void forward()
	{
		motor[FL] = 60;
		motor[BL] = 60;
		motor[FR] = -60;
		motor[BR] = -60;
	}

	void right()
	{
		motor[FL] = 60;
		motor[BL] = -60;
		motor[FR] = 60;
		motor[BR] = -60;
	}

	void left()
	{
		motor[FL] = -60;
		motor[BL] = 60;
		motor[FR] = -60;
		motor[BR] = 60;
	}

	void back()
	{
		motor[FL] = -60;
		motor[BL] = -60;
		motor[FR] = 60;
		motor[BR] = 60;
	}

	void spinright()
	{
		motor[FL] = 60;
		motor[BL] = 60;
		motor[FR] = 60;
		motor[BR] = 60;
	}

	void feed()
	{
		motor[Rbelt] = -60;
		motor[Lbelt] = 60;
	}

	void stopAll() {
		motor[BL] = motor[BR] = motor[FL] = motor[FR] = motor[Rbelt] = motor[Lbelt] = motor[Tilter] = 0;
	}
task main()
{
  initializeRobot();

  waitForStart();

  {forward();
  	wait10Msec(100);
  	stopAll();
  	right();
  	wait10Msec(250);
  	stopAll();
  	}
}
