#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Flipper,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Tilter,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     FR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     Belt,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SINE 0.707
#define COSINE 0.707
#define SPEED 0.8

#include "JoystickDriver.c"

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase



  int x, y, xs, xc, ys, yc, speed;




  while (true)
  {
	  if ( abs(joystick.joy1_x1) > 10 )
  		motor[FL] = motor[BL] = motor[FR] = motor[BR] = joystick.joy1_x1 * .75



  		;
  	else {
			x = joystick.joy1_x2;
			y = joystick.joy1_y2;
			if (abs(x) > 15 || abs(y) > 15) {
				xs = x * SINE;
				xc = x * COSINE;
				ys = y * SINE;
				yc = y * COSINE;
			if (joy1Btn(6))
			{speed = 20;
			}
			else if (joy1Btn(7))
			{speed = -20;
			}
			else
			{speed = 0;
			}
				motor[FR] = xc - ys;
				motor[FL] = xs + yc;

				motor[BR] = - motor[FL];
				motor[BL] = - motor[FR];
			}
			else {
				motor[FL] = motor[FR] = motor[BL] = motor[BR] = 0;
		}
	  motor[Belt] = -joystick.joy2_y2;

	  if
	  (joy2Btn(5))
		{motor[Flipper] = 20;
		}

		else if
		(joy2Btn(7))
		{motor[Flipper] = -100;
		}

		else
		{motor[Flipper] = .5;
		}

		if
		(joy2Btn(6))
		{motor[Tilter] = 80;
		}
		else if
		(joy2Btn(8))
		{motor[Tilter] = -80;
		}
		else
		{motor[Tilter] = 0;
		}
		if
		(joy1Btn(8))
		{motor[Flag] = 10;
		}
		else if
		(joy1Btn(7))
		{motor[Flag] = 100;
		}
		else
		{motor[Flag] = 0;
		}
			}
}
}
